import { mkdir, readdir, readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';

const root = process.cwd();
const contentDir = path.join(root, 'content/posts');
const output = path.join(root, 'src/data/generated.ts');

const parseFrontmatter = (raw) => {
  const match = raw.match(/^---\s*\n([\s\S]*?)\n---\s*\n([\s\S]*)$/);
  if (!match) return { meta: {}, content: raw.trim() };
  const meta = {};
  for (const line of match[1].split('\n')) {
    const separator = line.indexOf(':');
    if (separator < 0) continue;
    const key = line.slice(0, separator).trim();
    let value = line.slice(separator + 1).trim();
    if ((value.startsWith('"') && value.endsWith('"')) || (value.startsWith("'") && value.endsWith("'"))) value = value.slice(1, -1);
    if (value.startsWith('[') && value.endsWith(']')) value = value.slice(1, -1).split(',').map((item) => item.trim().replace(/^['"]|['"]$/g, '')).filter(Boolean);
    meta[key] = value;
  }
  return { meta, content: match[2].trim() };
};

const files = (await readdir(contentDir)).filter((file) => file.endsWith('.md')).sort();
const articles = [];
for (const file of files) {
  const raw = await readFile(path.join(contentDir, file), 'utf8');
  const { meta, content } = parseFrontmatter(raw);
  const slug = meta.slug || file.replace(/\.md$/, '');
  articles.push({
    id: meta.id || `post-${slug}`,
    slug,
    title: meta.title || slug,
    subtitle: meta.subtitle || '',
    excerpt: meta.excerpt || '',
    date: meta.date || '1970-01-01',
    category: meta.category || 'Notes',
    tags: Array.isArray(meta.tags) ? meta.tags : [],
    author: { name: meta.author || 'ReakNeel', avatar: meta.avatar || '', role: meta.role || 'Independent Engineer' },
    coverImage: meta.coverImage || '',
    readTimeMinutes: Number(meta.readTimeMinutes || 5),
    featured: String(meta.featured) === 'true',
    likes: 0,
    views: 0,
    aiSummary: meta.aiSummary || '',
    content,
  });
}

articles.sort((a, b) => new Date(b.date).getTime() - new Date(a.date).getTime());
await mkdir(path.dirname(output), { recursive: true });
await writeFile(output, `// Generated by scripts/build-content.mjs. Do not edit manually.\nimport type { Article } from '../types';\n\nexport const ARTICLES: Article[] = ${JSON.stringify(articles, null, 2)};\n`, 'utf8');
console.log(`Generated ${articles.length} posts -> ${path.relative(root, output)}`);
